# Generated by Django 5.0.1 on 2024-01-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Followers'),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Following'),
        ),
    ]
