# Generated by Django 5.0.1 on 2024-01-28 10:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saveddish',
            unique_together={('user_id', 'dish_id')},
        ),
    ]
